apiVersion: v1
kind: Service
metadata:
  name: python-flask-project-svc
spec:
  type: NodePort
  selector:
    app: python-flask-project
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
